---
format: 
  revealjs:
    slide-number: c/t
    footer: "Facultad de Ciencias, UNAM"
    center-title-slide: false
    code-overflow: wrap
    highlight-style: a11y
    height: 1080
    width: 1920
    chalkboard: true

execute: 
  eval: true
  echo: true
---

<h1>
<b>Visualizando una serie de tiempo</b><br>
<b></b>
</h1>

<hr>

<h2>
Algunas paqueterias en 
</h2>

<br>
<br>

<h3>Autor</h3>

<ul style="font-size: 1.2em;">
  <li>Rodrigo Basaldud</li>
</ul>

<br>

<h3>Semestre 2027-1</h3>


# La paqueteria `dygraphs`

<br>

::: {style="display: flex; justify-content: center;"}

```{r ejemplo1}
#| echo: true
#| fig-width: 10
#| fig-height: 4.5
#| fig-cap: "Ejemplo con dygraphs"

library(dygraphs)
lungDeaths <- cbind(ldeaths, mdeaths, fdeaths)

dygraph(lungDeaths,main="Muertes por cancer de pulmon 1974 - 1979") %>%
  dySeries("mdeaths", label = "Hombre") %>%
  dySeries("fdeaths", label = "Mujer") %>%
  dyOptions(stackedGraph = TRUE) %>%
  dyRangeSelector(height = 20) 

```

:::

--- 

Tambien se pueden personalizar otras cosas como:

<br>
<br>

```{r ejemplo2}
#| fig-width: 12
#| fig-height: 7
#| output-location: column

dygraph(lungDeaths, main = "Deaths from Lung Disease (UK)", width = "100%", height = "400px") %>%
  dyHighlight(highlightSeriesOpts = list(strokeWidth = 3))


```



---

Otra alternativa

```{r ejemplo3}
#| output-location: slide
#| fig-width: 15
#| fig-height: 8.5

dygraph(lungDeaths, main = "Deaths from Lung Disease (UK)",width = "100%") %>%
  dyHighlight(highlightSeriesOpts = list(strokeWidth = 5),
              highlightCircleSize = 5)

```









# La paqueteria `ggtime`





# La paqueteria `lubridate`


